# Generated by Django 3.2.12 on 2022-05-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0037_remove_empty_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('checkout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkout')),
            ],
            bases=('checkout.checkout',),
        ),
    ]
