# Generated by Django 3.2.12 on 2022-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='requested_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
