# Generated by Django 3.2.12 on 2022-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('attribute', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
